trigger: none # No CI Triggers

resources:
  repositories:
  - repository: templates
    type: git
    name: templates

variables:
- group: general
- group: apiRelated

pool: $(selfhostedpool)

stages:
- template: build_api_stage.yaml@templates
  parameters:
      apiName: 'consumer2'
      environmentName: 'dev'
      sonarqubeProjectKey: $(consumer2SQKey)
      sonarqubeProjectName: $(consumer2SQName)
      sonarqubeConnectionName: $(sqserviceconnection)

- template: docker_build_scan_push_stage.yaml@templates
  parameters:
      apiName: 'consumer2'
      environmentName: 'dev'
      repositoryName: 'consumer2'
      acrName: $(acrName)
